name: "\U0001F41B Bug Report"
description: "If something isn't working as expected \U0001F914"
labels: [ "type: bug" ]
title: 'bug: [DESCRIPTION]'

body:
  - type: input
    validations:
      required: true
    attributes:
      label: "Jan version"
      description: "**Tip:** The version is in the app's bottom right corner"
      placeholder: "e.g. 0.5.x-xxx"

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Describe the Bug"
      description: "A clear & concise description of the bug"

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: |
        Please list out steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'

  - type: textarea
    attributes:
      label: "Screenshots / Logs"
      description: |
        You can find logs in: ~/jan/logs/app.logs

  - type: checkboxes
    attributes:
      label: "What is your OS?"
      options:
        - label: MacOS
        - label: Windows
        - label: Linux
